apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sentinel
servers: 1
agents: 2
ports:
  - port: 514:30514/udp
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
