statefulset:
  replicas: 1
  podTemplate:
    spec:
      nodeSelector:
        workload: data
      tolerations:
        - key: workload
          value: data
          effect: NoSchedule

resources:
  cpu:
    cores: 1
  memory:
    container:
      max: 2Gi

storage:
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: local-path

tls:
  enabled: false

external:
  enabled: false
