apiVersion: v1
kind: Service
metadata:
  name: vector-syslog
  namespace: vector
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 514
      protocol: UDP
      nodePort: 30514
