apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yamenmehdizade/sentinel-platform.git
    targetRevision: main
    path: platform/cilium/policies
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
