apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: clickhouse-ingress
  namespace: data
spec:
  description: "ClickHouse-a yalniz Vector (8123), Risk Engine (9000) ve Grafana (9000)"
  endpointSelector:
    matchLabels:
      clickhouse.altinity.com/chi: sentinel
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: vector
            app.kubernetes.io/name: vector
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: sentinel
            app: risk-engine
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
