# grafana-policy.yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana-policy
  namespace: monitoring
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  ingress:
    # Brauzer (NodePort 30300) + kubelet health probe
    - fromEntities:
        - host
        - remote-node
        - world
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
  egress:
    # DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # ClickHouse datasource (native protokol)
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: data
            clickhouse.altinity.com/chi: sentinel
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
